spring:
  application:
    name: lumina-flashcard
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 9090
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 9000
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/flashcards_db
    username: flashcard_admin
    password: minhasenhaforte
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
app:
  jwt:
    secret: 'O9pZqBHUR1HeMYIRgoMWUOHSmRMhDfJVAOcld1NKy9Ah8jtRrnjkm4WMYHeUZJnQ'
    expirationMs: 86400000
---
logging:
  level:
    org.springframework.security: DEBUG